### PR TITLE
Feature/docs [WIP]

### PR DESCRIPTION
**Pull request by mgcth**
Add documentation for the package.

Can be found at: https://ingenjorsarbete-for-klimatet.github.io/smhi/

### CODE REVIEW

**Review by docNord — APPROVED** [review]
Nice Mladen!

When we are going to change the name of the package to include the ifk-prefix, this documentation needs to change as well, but until then I find it perfectly adequate.

**Comment by mgcth** [comment]
We could keep the name as `smhi`, but name the package `ifk-smhi`, i.e. loading and installing would use the `ifk` prefix but work here on github would just reference `smhi`, either works for me.

**Comment by mgcth** [comment]
@docNord, updated some intro text, feel free to suggest changes and then we can merge this and update it in the other PRs for each client.

**Review by docNord — DISMISSED** [review]
I think it looks really good. Two potential updates: 

1 - a code snippet to show how to get a sample data set for each of the building blocks

2 - a link to https://ingenjorsarbeteforklimatet.se at the bottom of the documentation.

**Comment by mgcth** [comment]
> I think it looks really good. Two potential updates:
> 
> 1 - a code snippet to show how to get a sample data set for each of the building blocks
> 
> 2 - a link to https://ingenjorsarbeteforklimatet.se at the bottom of the documentation.

Fixed 2. I think we can add 1 to the docs from the individual PRs after we merge this. Would be nice to include the vectorised logo here, though.

**Comment by mgcth** [comment]
@docNord logo in place, think this is good now.

**Review by docNord — APPROVED** [review]
Perfect!

**Pull request merged**
